input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    accel_profile = flat
    numlock_by_default = true

    sensitivity = 0

    touchpad {
        natural_scroll = false
    }
}

gestures {
    
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

binds {
    workspace_back_and_forth = false
}
